apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: poim-online-tls
spec:
  secretName: poim-online
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: poim.online
  dnsNames:
    - poim.online
    - www.poim.online